# Generated by Django 5.2.3 on 2025-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsb', '0002_alter_suggestion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
