# Generated by Django 5.2.4 on 2025-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsb', '0004_alter_suggestion_category_alter_suggestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
