services:
  - type: web
    name: nihub-dsb-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn nihub.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nihub-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: nihub-db
    plan: free
    databaseName: nihub_db
    user: nihub_user
